---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true
  PACKAGES: 'language-terraform'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable]
        tf_version:
        - '0.13.7'
        - '0.14.11'
        - '0.15.5'
        - '1.0.11'
        - '1.1.7'
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}
    - name: atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: install dependencies
      run: apm install && apm install ${PACKAGES} && apm clean
    - name: lint source and spec
      run: ./node_modules/.bin/eslint lib spec || true
    - name: install some pre-requisite packages
      run: sudo apt-get update && sudo apt-get -yq install curl xvfb libgbm-dev
    - name: install terraform
      run: curl -o terraform.zip https://releases.hashicorp.com/terraform/${{ matrix.tf_version }}/terraform_${{ matrix.tf_version }}_linux_amd64.zip && sudo unzip terraform.zip -d /usr/bin/
    - name: run tests
      run: atom --test spec
