---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '**.js'
  pull_request:
    branches: [master]
    paths:
    - '**.js'

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: node:14-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm install
    - name: lint source and spec
      run: ./node_modules/.bin/eslint lib spec || true
